version: '3.8'
services:
  api:
    build: .
    ports:
      - 3000:3000
    networks:
      - internal
    environment:
      AWS_ACCESS_KEY_ID: "minioadmin"
      AWS_SECRET_ACCESS_KEY: "minioadmin"
      AWS_ENDPOINT: "http://minio:9000"
      AWS_PUBLIC_ENDPOINT: "http://localhost:9090"

  minio:
    image: minio/minio
    command: [server, /data]
    ports:
      - 9090:9000
    networks:
      - internal
    volumes:
      - minio_data:/data

  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - internal
    volumes:
      - redis_data:/data


networks:
  internal:

volumes:
  minio_data:
  redis_data:
